TYPE=AYST

[Metadata]
AppName=Yara.SDI
Description=RGVjcnlwdCBTdHJpbmdzIFVzaW5nIEludm9rZXMgLSBSZXNvbHZlIFN0cmluZ3MgaW4gLk5FVCBBcHBsaWNhdGlvbnMNCg0KVGhpcyB0b29sIG11c3Qgb25seSBiZSB1c2VkIGlmOg0KDQotIFlvdXIgdGFyZ2V0IHNhbXBsZSBpcyBzYWZlIHRvIHJ1biBzaW5jZSBTREkgd2lsbCBydW4gcGFydHMgb2YgaXRzIGNvZGUuDQotIE5vIHN0YXRpYyBzb2x1dGlvbnMgd2VyZSBhYmxlIHRvIHNvbHZlIHRoZSBwcm90ZWN0aW9uLg
Icon=
RepoURL=https://github.com/yara-ch/SDI/

[Versions]
1.0=https://github.com/yara-ch/SDI/releases/download/v1.0/Yara.SDI.zip
