TYPE=AYST

[Metadata]
AppName=Yara.SDI
Description=RGVjcnlwdCBTdHJpbmdzIFVzaW5nIEludm9rZXMgLSBSZXNvbHZlIFN0cmluZ3MgaW4gLk5FVCBBcHBsaWNhdGlvbnMNCg0KVGhpcyB0b29sIG11c3Qgb25seSBiZSB1c2VkIGlmOg0KDQotIFlvdXIgdGFyZ2V0IHNhbXBsZSBpcyBzYWZlIHRvIHJ1biBzaW5jZSBpdCB3aWxsIHJ1biBwYXJ0cyBvZiBpdHMgY29kZS4NCi0gTm8gc3RhdGljIHNvbHV0aW9ucyB3ZXJlIGFibGUgdG8gc29sdmUgdGhlIHByb3RlY3Rpb24u
Icon=
RepoURL=https://github.com/yara-ch/SDI/

[Versions]
1.0=https://github.com/yara-ch/SDI/releases/download/v1.0/Yara.SDI.zip
